CREATE DATABASE IF NOT EXISTS clicktail

CREATE TABLE IF NOT EXISTS clicktail.mysql_slow_log
(
    `_time` DateTime,
    `_date` Date default toDate(`_time`),
    `_ms` UInt32,
    client String,
    query String,
    normalized_query String,
    query_time Float32,
    user String,
    statement String,
    tables String,
    schema String,
    rows_examined UInt32,
    rows_sent UInt32,
    lock_time Float32,
    connection_id UInt32,
    error_num UInt32,
    killed UInt16,
    rows_affected UInt32,
    database String,
    comments String,
    bytes_sent UInt32,
    tmp_tables UInt8,
    tmp_disk_tables UInt8,
    tmp_table_sizes UInt32,
    transaction_id String,
    query_cache_hit UInt8,
    full_scan UInt8,
    full_join UInt8,
    tmp_table UInt8,
    tmp_table_on_disk UInt8,
    filesort UInt8,
    filesort_on_disk UInt8,
    merge_passes UInt32,
    IO_r_ops UInt32,
    IO_r_bytes UInt32,
    IO_r_wait_sec Float32,
    rec_lock_wait_sec Float32,
    queue_wait_sec Float32,
    pages_distinct UInt32,
    sl_rate_type String,
    sl_rate_limit UInt16,
    hosted_on String,
    read_only UInt8,
    replica_lag UInt64,
    role String
) ENGINE = MergeTree(`_date`, (`_time`, query), 8192);

CREATE TABLE IF NOT EXISTS clicktail.mysql_audit_log
(
    `_time` DateTime,
    `_date` Date default toDate(`_time`),
    `_ms` UInt32,
    command_class String,
    connection_id UInt32,
    db String,
    host String,
    ip String,
    name String,
    os_user String,
    os_login String,
    os_version String,
    mysql_version String,
    priv_user String,
    proxy_user String,
    record String,
    sqltext String,
    status UInt32,
    user String,
    startup_optionsi String
) ENGINE = MergeTree(`_date`, (`_time`, host, user), 8192);


CREATE TABLE IF NOT EXISTS clicktail.nginx_log
(
    `_time` DateTime,
    `_date` Date default toDate(`_time`),
    `_ms` UInt32,
    body_bytes_sent UInt32,
    http_user_agent String,
    http_referer String,
    remote_addr String,
    request String,
    request_method String,
    request_uri String,
    query_string String,
    remote_user String,
    status UInt32,
    domain String,
    request_length UInt32,
    url String,
    cookie String,
    geoip String,
    ipip String,
    useragent String,
    cookies String,
    referers String,
    request_id String,
) ENGINE = MergeTree(`_date`, (`_time`, request_method, status), 8192)