{
 "title": "Jaeger collector",
 "tags": [ "generated" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "common_labels",
    "label": "common_labels",
    "query": "job=\"jaeger-collector\""
   }
  ]
 },
 "panels": [
  {
   "title": "by client service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans received (by service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "spans / second" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (\n  irate(\n    jaeger_collector_spans_by_svc{${common_labels}}[5m]\n  )\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Spans saved (by service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "spans / second" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (\n  irate(\n    jaeger_collector_spans_saved_by_svc{${common_labels}}[5m]\n  )\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Debug spans received (by service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "spans / second" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (\n  irate(\n    jaeger_collector_debug_spans_by_svc{${common_labels}}[5m]\n  )\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Debug spans saved (by service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "spans / second" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (\n  irate(\n    jaeger_collector_debug_spans_saved_by_svc{${common_labels}}[5m]\n  )\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Traces received (by service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "traces / second" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (\n  irate(\n    jaeger_collector_traces_by_svc{${common_labels}}[5m]\n  )\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Traces saved (by service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "traces / second" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (\n  irate(\n    jaeger_collector_traces_saved_by_svc{${common_labels}}[5m]\n  )\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  { "title": "by jaeger-collector instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Spans received (by instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "spans / second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(\n    jaeger_collector_spans_recd{${common_labels}}[5m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "\"too busy\" errors (by instance)",
   "type": "graph",
   "description": "Errors handling spans because the server was too busy",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "errors / second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(\n    jaeger_collector_error_busy{${common_labels}}[5m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Spans dropped (by instance)",
   "type": "graph",
   "description": "Spans dropped because the queue was full",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "spans / second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(\n    jaeger_collector_spans_dropped{${common_labels}}[5m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Spans rejected (by instance)",
   "type": "graph",
   "description": "Not dropped - actively rejected.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "spans / second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(\n    jaeger_collector_spans_rejected{${common_labels}}[5m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jaeger-collector process metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (\n  irate(\n    process_cpu_seconds_total{${common_labels}}[5m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "memory RSS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (\n  process_resident_memory_bytes{${common_labels}}\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}